import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

type DeploymentsData = {
	evm: string | null;
	pvm: string | null;
	evmPredictionMarket: string | null;
};

function readDeployments(): DeploymentsData {
	const fallback: DeploymentsData = {
		evm: null,
		pvm: null,
		evmPredictionMarket: null,
	};
	try {
		const parsed = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
		return { ...fallback, ...parsed };
	} catch {
		return fallback;
	}
}

function writeDeployments(data: DeploymentsData) {
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tevmPredictionMarket: string | null;
} = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tevmPredictionMarket: ${fmt(data.evmPredictionMarket)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function deploy(name: string): Promise<string> {
	const [walletClient] = await hre.viem.getWalletClients();
	const publicClient = await hre.viem.getPublicClient();
	const artifact = await hre.artifacts.readArtifact(name);

	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}
	return receipt.contractAddress;
}

async function main() {
	const data = readDeployments();

	console.log("Deploying ProofOfExistence (EVM/solc)...");
	data.evm = await deploy("ProofOfExistence");
	console.log(`EVM ProofOfExistence deployed to: ${data.evm}`);

	console.log("Deploying PredictionMarket (EVM/solc)...");
	data.evmPredictionMarket = await deploy("PredictionMarket");
	console.log(`EVM PredictionMarket deployed to: ${data.evmPredictionMarket}`);

	writeDeployments(data);
	console.log("Updated deployments.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
