// Auto-generated by contract deploy scripts — do not edit manually
export type NetworkKey = "local" | "paseoHub";

export type NetworkDeployments = {
	evm: string | null;
	pvm: string | null;
	evmPredictionMarket: string | null;
};

export const deployments: Record<NetworkKey, NetworkDeployments> = {
	local: {
		evm: "0xc01ee7f10ea4af4673cfff62710e1d7792aba8f3",
		pvm: "0x962c0940d72e7db6c9a5f81f1ca87d8db2b82a23",
		evmPredictionMarket: "0x970951a12f975e6762482aca81e57d5a2a4e73f4",
	},
	paseoHub: {
		evm: "0xd4410802eb45cf1ad6b1f5e81693b4dc9a1c2987",
		pvm: "0xf9d3bdb49097c775db7ddbda2d2968cea63a4b90",
		evmPredictionMarket: "0x6a05cc02debe2d03250f9dfc257ded87d1cb4736",
	},
};
