// Auto-generated by contract deploy scripts — do not edit manually
export type NetworkKey = "local" | "paseoHub";

export type NetworkDeployments = {
	evm: string | null;
	pvm: string | null;
	evmPredictionMarket: string | null;
};

export const deployments: Record<NetworkKey, NetworkDeployments> = {
	local: {
		evm: "0xc01ee7f10ea4af4673cfff62710e1d7792aba8f3",
		pvm: "0x962c0940d72e7db6c9a5f81f1ca87d8db2b82a23",
		evmPredictionMarket: "0x970951a12f975e6762482aca81e57d5a2a4e73f4",
	},
	paseoHub: {
		evm: "0xd9bf9aab35e725669fcea0a129d43a302f2d8f1a",
		pvm: "0xdfd20955f3570f3ba2a9bc88f59c279165c4fe51",
		evmPredictionMarket: "0x59c8f7c9d9209af4f4f52605e3999381b41698ea",
	},
};
