// Auto-generated by contract deploy scripts — do not edit manually
export type NetworkKey = "local" | "testnet";

export type NetworkDeployments = {
	evm: string | null;
	pvm: string | null;
	evmPredictionMarket: string | null;
};

export const deployments: Record<NetworkKey, NetworkDeployments> = {
	local: {
		evm: "0x3469e1dac06611030aece8209f07501e9a7acc69",
		pvm: "0x867fb76ba206040ea09e73f38eda307413d4966f",
		evmPredictionMarket: "0x7d4567b7257cf869b01a47e8cf0edb3814bdb963",
	},
	testnet: {
		evm: "0xd9bf9aab35e725669fcea0a129d43a302f2d8f1a",
		pvm: "0xdfd20955f3570f3ba2a9bc88f59c279165c4fe51",
		evmPredictionMarket: "0x59c8f7c9d9209af4f4f52605e3999381b41698ea",
	},
};
