import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

export type NetworkKey = "local" | "testnet" | "paseoHub";

export type NetworkDeployments = {
	evm: string | null;
	pvm: string | null;
	evmPredictionMarket: string | null;
};

export type DeploymentsFile = Record<NetworkKey, NetworkDeployments>;

const EMPTY_NETWORK: NetworkDeployments = {
	evm: null,
	pvm: null,
	evmPredictionMarket: null,
};

const EMPTY_FILE: DeploymentsFile = {
	local: { ...EMPTY_NETWORK },
	testnet: { ...EMPTY_NETWORK },
	paseoHub: { ...EMPTY_NETWORK },
};

export function networkKeyForChainId(chainId: number): NetworkKey | null {
	if (chainId === 420420421) return "local";
	if (chainId === 420420417) return "testnet";
	return null;
}

function mergeNetwork(
	partial: Partial<NetworkDeployments> | undefined,
): NetworkDeployments {
	return { ...EMPTY_NETWORK, ...(partial ?? {}) };
}

export function readDeployments(): DeploymentsFile {
	try {
		const raw = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) as
			| Partial<DeploymentsFile>
			| (NetworkDeployments & Partial<DeploymentsFile>);

		if (
			raw &&
			typeof raw === "object" &&
			("local" in raw || "testnet" in raw || "paseoHub" in raw)
		) {
			const parsed = raw as Partial<DeploymentsFile>;
			return {
				local: mergeNetwork(parsed.local),
				testnet: mergeNetwork(parsed.testnet),
				paseoHub: mergeNetwork(parsed.paseoHub),
			};
		}

		const legacy = raw as Partial<NetworkDeployments>;
		if (legacy && typeof legacy === "object") {
			return {
				local: mergeNetwork(legacy),
				testnet: { ...EMPTY_NETWORK },
				paseoHub: { ...EMPTY_NETWORK },
			};
		}
	} catch {
		// fall through to EMPTY_FILE
	}
	return {
		local: { ...EMPTY_NETWORK },
		testnet: { ...EMPTY_NETWORK },
		paseoHub: { ...EMPTY_NETWORK },
	};
}

export function writeDeployments(data: DeploymentsFile): void {
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const renderNetwork = (n: NetworkDeployments) => `{
\t\tevm: ${fmt(n.evm)},
\t\tpvm: ${fmt(n.pvm)},
\t\tevmPredictionMarket: ${fmt(n.evmPredictionMarket)},
\t}`;

	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export type NetworkKey = "local" | "testnet" | "paseoHub";

export type NetworkDeployments = {
\tevm: string | null;
\tpvm: string | null;
\tevmPredictionMarket: string | null;
};

export const deployments: Record<NetworkKey, NetworkDeployments> = {
\tlocal: ${renderNetwork(data.local)},
\ttestnet: ${renderNetwork(data.testnet)},
\tpaseoHub: ${renderNetwork(data.paseoHub)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

export function updateContract(
	data: DeploymentsFile,
	network: NetworkKey,
	contract: keyof NetworkDeployments,
	address: string,
): DeploymentsFile {
	return {
		...data,
		[network]: {
			...data[network],
			[contract]: address,
		},
	};
}
