import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

export type NetworkKey = "local" | "paseoHub";

export type NetworkDeployments = {
	evm: string | null;
	pvm: string | null;
	evmPredictionMarket: string | null;
};

export type DeploymentsFile = Record<NetworkKey, NetworkDeployments>;

const EMPTY_NETWORK: NetworkDeployments = {
	evm: null,
	pvm: null,
	evmPredictionMarket: null,
};

const LOCAL_CHAIN_ID = 420420421;

export function networkKeyForChainId(chainId: number): NetworkKey {
	return chainId === LOCAL_CHAIN_ID ? "local" : "paseoHub";
}

function mergeNetwork(partial: Partial<NetworkDeployments> | undefined): NetworkDeployments {
	return { ...EMPTY_NETWORK, ...(partial ?? {}) };
}

export function readDeployments(): DeploymentsFile {
	try {
		const raw = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) as
			| Partial<DeploymentsFile & { testnet: Partial<NetworkDeployments> }>
			| (NetworkDeployments & Partial<DeploymentsFile>);

		if (
			raw &&
			typeof raw === "object" &&
			("local" in raw || "paseoHub" in raw || "testnet" in raw)
		) {
			const parsed = raw as Partial<
				DeploymentsFile & { testnet: Partial<NetworkDeployments> }
			>;
			return {
				local: mergeNetwork(parsed.local),
				paseoHub: mergeNetwork(parsed.paseoHub ?? parsed.testnet),
			};
		}

		const legacy = raw as Partial<NetworkDeployments>;
		if (legacy && typeof legacy === "object") {
			return {
				local: mergeNetwork(legacy),
				paseoHub: { ...EMPTY_NETWORK },
			};
		}
	} catch {
		// fall through to EMPTY_FILE
	}
	return {
		local: { ...EMPTY_NETWORK },
		paseoHub: { ...EMPTY_NETWORK },
	};
}

export function writeDeployments(data: DeploymentsFile): void {
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const renderNetwork = (n: NetworkDeployments) => `{
\t\tevm: ${fmt(n.evm)},
\t\tpvm: ${fmt(n.pvm)},
\t\tevmPredictionMarket: ${fmt(n.evmPredictionMarket)},
\t}`;

	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export type NetworkKey = "local" | "paseoHub";

export type NetworkDeployments = {
\tevm: string | null;
\tpvm: string | null;
\tevmPredictionMarket: string | null;
};

export const deployments: Record<NetworkKey, NetworkDeployments> = {
\tlocal: ${renderNetwork(data.local)},
\tpaseoHub: ${renderNetwork(data.paseoHub)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

export function updateContract(
	data: DeploymentsFile,
	network: NetworkKey,
	contract: keyof NetworkDeployments,
	address: string,
): DeploymentsFile {
	return {
		...data,
		[network]: {
			...data[network],
			[contract]: address,
		},
	};
}
